package com.fut.desktop.app.parameters;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Random;

@SuppressWarnings("WeakerAccess")
public class Team extends SearchParameterBase<Long> {

    public final static long Heidenheim1846 = 111235;
    public final static long Kaiserslautern = 29;
    public final static long Koln = 31;
    public final static long Nurnberg = 171;
    public final static long UnionBerlin = 1831;
    public final static long Mainz05 = 169;
    public final static long AalborgBK = 820;
    public final static long AalesundsFK = 1755;
    public final static long AarhusGF = 271;
    public final static long Aberdeen = 77;
    public final static long ACHorsens = 1446;
    public final static long AccringtonStanley = 110313;
    public final static long ADAlcorcon = 100831;
    public final static long Adanaspor = 110401;
    public final static long AdelaideUnited = 111393;
    public final static long ADODenHaag = 650;
    public final static long AFCWimbledon = 112259;
    public final static long AIK = 433;
    public final static long AJAuxerre = 57;
    public final static long Ajax = 245;
    public final static long AkhisarBelediyespor = 111340;
    public final static long AlAhli = 112387;
    public final static long AlBatin = 112990;
    public final static long AlFaisaly = 112389;
    public final static long AlFateh = 112390;
    public final static long AlHilal = 605;
    public final static long AlIttihad = 607;
    public final static long AlKhaleej = 112883;
    public final static long AlNassr = 112139;
    public final static long AlQadisiyah = 112391;
    public final static long AlRaed = 112392;
    public final static long AlShabab = 111674;
    public final static long AlTaawoun = 112393;
    public final static long AlWehda = 112408;
    public final static long Alanyaspor = 113142;
    public final static long AlbirexNiigata = 112906;
    public final static long AlianzaPetrolera = 112579;
    public final static long AmiensSC = 1816;
    public final static long AmkarPerm = 110234;
    public final static long AngersSCO = 1530;
    public final static long Antalyaspor = 741;
    public final static long ArkaGdynia = 111082;
    public final static long Arsenal = 1;
    public final static long ArsenaldeSarandi = 110394;
    public final static long ASMonacoFootballClubSA = 69;
    public final static long ASNancyLorraine = 1823;
    public final static long ASSaintEtienne = 1819;
    public final static long Ascoli = 1847;
    public final static long AstonVilla = 2;
    public final static long Atalanta = 39;
    public final static long AthleticClub = 448;
    public final static long AthleticClubAjaccio = 614;
    public final static long AtikerKonyaspor = 101033;
    public final static long AtleticoBucaramanga = 112992;
    public final static long AtleticodeRafaela = 110392;
    public final static long AtleticoHuila = 112528;
    public final static long AtleticoMadrid = 240;
    public final static long AtleticoNacional = 101100;
    public final static long AtleticoTucuman = 111708;
    public final static long AudaxItaliano = 101097;
    public final static long Avellino = 2038;
    public final static long AvispaFukuoka = 113186;
    public final static long AZ = 1906;
    public final static long Bari = 1848;
    public final static long Barnet = 135;
    public final static long Barnsley = 1932;
    public final static long Bayer04Leverkusen = 32;
    public final static long BelgranodeCordoba = 111022;
    public final static long Benevento = 112026;
    public final static long BesiktasJK = 327;
    public final static long BirminghamCity = 88;
    public final static long BKHacken = 711;
    public final static long BlackburnRovers = 3;
    public final static long Blackpool = 1926;
    public final static long BoavistaFC = 1898;
    public final static long BocaJuniors = 1877;
    public final static long BohemianFC = 305;
    public final static long Bologna = 189;
    public final static long BoltonWanderers = 4;
    public final static long BorussiaDortmund = 22;
    public final static long BorussiaMonchengladbach = 23;
    public final static long BourgenBressePeronnas01 = 110576;
    public final static long Bournemouth = 1943;
    public final static long BoyacaChicoFC = 112019;
    public final static long BradfordCity = 1804;
    public final static long BrayWanderers = 838;
    public final static long Brentford = 1925;
    public final static long Brescia = 190;
    public final static long BrightonHoveAlbion = 1808;
    public final static long BrisbaneRoar = 111395;
    public final static long BristolCity = 1919;
    public final static long BristolRovers = 1962;
    public final static long BrondbyIF = 269;
    public final static long BrukBetTermalicaNieciecza = 112510;
    public final static long BSCYoungBoys = 900;
    public final static long Burnley = 1796;
    public final static long Bursaspor = 742;
    public final static long BurtonAlbion = 15015;
    public final static long Bury = 1945;
    public final static long CAOsasuna = 479;
    public final static long CadizCF = 1968;
    public final static long Cagliari = 1842;
    public final static long CambridgeUnited = 1944;
    public final static long CardiffCity = 1961;
    public final static long CarlisleUnited = 1480;
    public final static long Carpi = 112409;
    public final static long CaykurRizespor = 101037;
    public final static long CDAntofagasta = 112533;
    public final static long CDCobresal = 110978;
    public final static long CDEvertondeVinadelMar = 112584;
    public final static long CDHuachipato = 111327;
    public final static long CDLeganes = 100888;
    public final static long CDLugo = 110831;
    public final static long CDMirandes = 110069;
    public final static long CDNacional = 1891;
    public final static long CDNumancia = 477;
    public final static long CDOHiggins = 112116;
    public final static long CDPalestino = 111328;
    public final static long CDTenerife = 260;
    public final static long CDUniversidaddeConcepcion = 112534;
    public final static long Celtic = 78;
    public final static long CentralCoastMariners = 111396;
    public final static long Cesena = 110915;
    public final static long CFOsBelenenses = 1889;
    public final static long CFReus = 110854;
    public final static long ChamoisNiortaisFootballClub = 1813;
    public final static long CharltonAthletic = 89;
    public final static long Chaves = 518;
    public final static long Chelsea = 5;
    public final static long CheltenhamTown = 1936;
    public final static long Chesterfield = 1924;
    public final static long Chiavari = 113147;
    public final static long ChicagoFireSoccerClub = 693;
    public final static long ChievoVerona = 192;
    public final static long Cittadella = 111993;
    public final static long ClermontFoot63 = 1815;
    public final static long ClubAmerica = 1879;
    public final static long ClubAtlas = 101114;
    public final static long ClubAtleticoAldosivi = 111707;
    public final static long ClubAtleticoBanfield = 110404;
    public final static long ClubAtleticoHuracan = 111711;
    public final static long ClubAtleticoLanus = 110395;
    public final static long ClubAtleticoSarmiento = 112713;
    public final static long ClubAtleticoTalleres = 112670;
    public final static long ClubAtleticoTemperley = 112904;
    public final static long ClubBruggeKV = 231;
    public final static long ClubDeportesTemuco = 112709;
    public final static long ClubLeon = 110781;
    public final static long ClubNecaxa = 101121;
    public final static long ClubOlimpo = 110398;
    public final static long ClubTijuana = 111678;
    public final static long ColchesterUnited = 1935;
    public final static long ColoColo = 110980;
    public final static long ColondeSantaFe = 110406;
    public final static long ColoradoRapids = 694;
    public final static long ColumbusCrewSC = 687;
    public final static long CordobaCF = 1867;
    public final static long CorkCity = 422;
    public final static long CorporacionClubDeportivoTulua = 112934;
    public final static long CoventryCity = 1800;
    public final static long Cracovia = 110747;
    public final static long CrawleyTown = 110890;
    public final static long CreweAlexandra = 121;
    public final static long Crotone = 110734;
    public final static long CruzAzul = 1878;
    public final static long CrystalPalace = 1799;
    public final static long CSMaritimo = 1893;
    public final static long CSKAMoscow = 315;
    public final static long DAlaves = 463;
    public final static long DCUnited = 688;
    public final static long DefensayJusticia = 111710;
    public final static long DeportesIquique = 112531;
    public final static long DeportesTolima = 111722;
    public final static long DeportivoCali = 101102;
    public final static long DeportivoPasto = 111723;
    public final static long DeportivoToluca = 1882;
    public final static long DerbyCounty = 91;
    public final static long DerryCity = 445;
    public final static long DijonFCO = 110569;
    public final static long DjurgardensIF = 710;
    public final static long DoncasterRovers = 142;
    public final static long DSCArminiaBielefeld = 159;
    public final static long Dundalk = 837;
    public final static long DundeeFC = 180;
    public final static long EintrachtBraunschweig = 110500;
    public final static long EintrachtFrankfurt = 1824;
    public final static long ElcheCF = 468;
    public final static long Empoli = 1746;
    public final static long EnAvantdeGuingamp = 62;
    public final static long EnvigadoFC = 112526;
    public final static long EsbjergfB = 1445;
    public final static long ESTACTroyes = 294;
    public final static long EstorilPraia = 10020;
    public final static long EstudiantesdeLaPlata = 101083;
    public final static long EttifaqFC = 112096;
    public final static long Everton = 7;
    public final static long Excelsior = 1971;
    public final static long ExeterCity = 143;
    public final static long FSantaMariadaFeira = 10019;
    public final static long FCTokyo = 101150;
    public final static long FalkenbergsFF = 112169;
    public final static long FCAdmiraWackerModling = 111821;
    public final static long FCAnzhiMakhachkala = 100766;
    public final static long FCArouca = 112513;
    public final static long FCArsenalTula = 110756;
    public final static long FCAugsburg = 100409;
    public final static long FCBarcelona = 241;
    public final static long FCBasel = 896;
    public final static long FCBayernMunchen = 21;
    public final static long FCDallas = 695;
    public final static long FCErzgebirgeAue = 506;
    public final static long FCGirondinsdeBordeaux = 59;
    public final static long FCGroningen = 1915;
    public final static long FCIngolstadt04 = 111239;
    public final static long FCKobenhavn = 819;
    public final static long FCKrasnodar = 112218;
    public final static long FCKrylyaSovetovSamara = 100764;
    public final static long FCLausanneSport = 1862;
    public final static long FCLorient = 217;
    public final static long FCLugano = 10032;
    public final static long FCLuzern = 897;
    public final static long FCMidtjylland = 1516;
    public final static long FCNantes = 71;
    public final static long FCNordsjaelland = 1788;
    public final static long FCOrenburg = 112261;
    public final static long FCPacosdeFerreira = 1892;
    public final static long FCPorto = 236;
    public final static long FCRedBullSalzburg = 191;
    public final static long FCRostov = 110231;
    public final static long FCSchalke04 = 34;
    public final static long FCSeoul = 982;
    public final static long FCSion = 110770;
    public final static long FCSochauxMontbeliard = 226;
    public final static long FCStGallen = 898;
    public final static long FCStPauliHamburg = 110329;
    public final static long FCThun = 1715;
    public final static long FCTomTomsk = 110233;
    public final static long FCTwente = 1908;
    public final static long FCUfa = 110822;
    public final static long FCUral = 111264;
    public final static long FCUtrecht = 1903;
    public final static long FCVaduz = 286;
    public final static long FCWurzburgerKickers = 110197;
    public final static long FenerbahceSK = 326;
    public final static long Ferrara = 112791;
    public final static long Feyenoord = 246;
    public final static long FinnHarps = 111131;
    public final static long Fiorentina = 110374;
    public final static long FKAustriaWien = 256;
    public final static long FKBodoGlimt = 918;
    public final static long FKHaugesund = 1463;
    public final static long FleetwoodTown = 112260;
    public final static long FootballClubdeMetz = 68;
    public final static long FortalezaCEIF = 112834;
    public final static long FortunaDusseldorf = 110636;
    public final static long Frosinone = 111657;
    public final static long Fulham = 144;
    public final static long GalatasaraySK = 325;
    public final static long GalwayUnited = 1571;
    public final static long GambaOsaka = 112093;
    public final static long GazelecFootballClubAjaccio = 110316;
    public final static long Gaziantepspor = 101024;
    public final static long GefleIF = 111277;
    public final static long GenclerbirligiSK = 101025;
    public final static long Genoa = 110556;
    public final static long GetafeCF = 1860;
    public final static long GIFSundsvall = 1596;
    public final static long Gillingham = 1802;
    public final static long GimnasiayEsgrimaLaPlata = 101084;
    public final static long GironaFC = 110062;
    public final static long GoAheadEagles = 100632;
    public final static long GodoyCruz = 111706;
    public final static long GornikLeczna = 110565;
    public final static long GranadaCF = 110832;
    public final static long GrasshopperClubZurich = 322;
    public final static long GrimsbyTown = 92;
    public final static long Guadalajara = 1880;
    public final static long GwangJuFC = 112258;
    public final static long HamburgerSV = 28;
    public final static long HamiltonAcademicalFC = 184;
    public final static long HammarbyIF = 708;
    public final static long Hannover96 = 485;
    public final static long HartlepoolUnited = 1941;
    public final static long HavreAthleticClub = 1738;
    public final static long HeartofMidlothian = 80;
    public final static long HellasVerona = 206;
    public final static long HelsingborgsIF = 432;
    public final static long HeraclesAlmelo = 100634;
    public final static long HerthaBerlin = 166;
    public final static long HJKHelsinki = 100325;
    public final static long HolsteinKiel = 576;
    public final static long HoustonDynamo = 698;
    public final static long HuddersfieldTown = 1939;
    public final static long HullCity = 1952;
    public final static long IFElfsborg = 700;
    public final static long IFKGoteborg = 319;
    public final static long IFKNorrkoping = 702;
    public final static long IKStart = 1524;
    public final static long IncheonUnitedFC = 110765;
    public final static long Independiente = 110093;
    public final static long IndependienteMedellin = 101103;
    public final static long IndependienteSantaFe = 101104;
    public final static long Inter = 44;
    public final static long InvernessCaledonianThistle = 620;
    public final static long IpswichTown = 94;
    public final static long JagielloniaBialystok = 110745;
    public final static long JaguaresdeChiapas = 112679;
    public final static long JaguaresFutbolClub = 112903;
    public final static long JejuUnitedFC = 1478;
    public final static long JeonbukHyundaiMotors = 1477;
    public final static long JeonnamDragons = 1475;
    public final static long JonkopingsSodraIF = 112130;
    public final static long JubiloIwata = 101144;
    public final static long JuniorFC = 101101;
    public final static long Juventus = 45;
    public final static long KAAGent = 674;
    public final static long KaizerChiefs = 110929;
    public final static long KalmarFF = 1439;
    public final static long KardemirKarabukspor = 112122;
    public final static long KarlsruherSC = 1832;
    public final static long KASEupen = 2013;
    public final static long KashimaAntlers = 101147;
    public final static long KashiwaReysol = 101145;
    public final static long KasimpasaSK = 111339;
    public final static long KawasakiFrontale = 111730;
    public final static long Kayserispor = 101020;
    public final static long Kilmarnock = 82;
    public final static long KoronaKielce = 111083;
    public final static long KRCGenk = 673;
    public final static long KVKortrijk = 100081;
    public final static long KVMechelen = 110724;
    public final static long KVOostende = 682;
    public final static long KVCWesterlo = 681;
    public final static long LaEquidad = 112523;
    public final static long LAGalaxy = 697;
    public final static long LaSpezia = 110741;
    public final static long Latina = 112487;
    public final static long Lazio = 46;
    public final static long LechPoznan = 873;
    public final static long LechiaGdansk = 111091;
    public final static long LeedsUnited = 8;
    public final static long Legends = 112658;
    public final static long LegiaWarszawa = 1871;
    public final static long LeicesterCity = 95;
    public final static long LevanteUD = 1853;
    public final static long LeytonOrient = 1958;
    public final static long LillestromSK = 299;
    public final static long Liniers = 101088;
    public final static long Liverpool = 9;
    public final static long LokomotivMoscow = 100765;
    public final static long LongfordTown = 1586;
    public final static long LOSCLille = 65;
    public final static long LutonTown = 1923;
    public final static long LyngbyBK = 15001;
    public final static long MalagaCF = 573;
    public final static long MalmoFF = 320;
    public final static long ManchesterCity = 10;
    public final static long ManchesterUnited = 11;
    public final static long MansfieldTown = 1940;
    public final static long MedipolBasaksehirFK = 101014;
    public final static long MelbourneCity = 112224;
    public final static long MelbourneVictory = 111397;
    public final static long Middlesbrough = 12;
    public final static long Milan = 47;
    public final static long MillonariosFC = 101105;
    public final static long Millwall = 97;
    public final static long MiltonKeynesDons = 1798;
    public final static long MoldeFK = 417;
    public final static long MonarcasMorelia = 1028;
    public final static long Monterrey = 1032;
    public final static long MontpellierHeraultSC = 70;
    public final static long MontrealImpact = 111139;
    public final static long Morecambe = 357;
    public final static long MoreirenseFC = 1900;
    public final static long Motherwell = 83;
    public final static long NEC = 1910;
    public final static long NagoyaGrampus = 112092;
    public final static long Napoli = 48;
    public final static long Nastic = 15019;
    public final static long NewEnglandRevolution = 691;
    public final static long NewYorkCityFootballClub = 112828;
    public final static long NewYorkRedBulls = 689;
    public final static long NewcastleJets = 111398;
    public final static long NewcastleUnited = 13;
    public final static long NewellsOldBoys = 110396;
    public final static long NewportCounty = 112254;
    public final static long NimesOlympique = 224;
    public final static long NorthamptonTown = 1930;
    public final static long NorwichCity = 1792;
    public final static long NottinghamForest = 14;
    public final static long NottsCounty = 1937;
    public final static long Novara = 112225;
    public final static long OddsBK = 1456;
    public final static long OdenseBoldklub = 272;
    public final static long OGCNice = 72;
    public final static long OldhamAthletic = 1920;
    public final static long OlympiacosCFP = 280;
    public final static long OlympiquedeMarseille = 219;
    public final static long OlympiqueLyonnais = 66;
    public final static long OmiyaArdija = 112345;
    public final static long OnceCaldas = 101106;
    public final static long OrebroSK = 705;
    public final static long OrlandoCitySoccerClub = 112606;
    public final static long OrlandoPirates = 110930;
    public final static long Osmanlispor = 112958;
    public final static long OstersundsFK = 113173;
    public final static long OxfordUnited = 1951;
    public final static long Pachuca = 110147;
    public final static long Palermo = 1843;
    public final static long PanathinaikosFC = 1884;
    public final static long PAOK = 393;
    public final static long ParisSaintGermain = 73;
    public final static long PartickThistleFC = 1754;
    public final static long PatriotasBoyacaFC = 112527;
    public final static long Patronato = 110581;
    public final static long PECZwolle = 1914;
    public final static long PerthGlory = 111399;
    public final static long Perugia = 199;
    public final static long Pescara = 200;
    public final static long PeterboroughUnited = 1938;
    public final static long PhiladelphiaUnion = 112134;
    public final static long PiastGliwice = 111086;
    public final static long Pisa = 110738;
    public final static long PlymouthArgyle = 1929;
    public final static long PogonSzczecin = 110746;
    public final static long PohangSteelers = 1474;
    public final static long PortVale = 1928;
    public final static long PortlandTimbers = 111140;
    public final static long Portsmouth = 1790;
    public final static long PrestonNorthEnd = 1801;
    public final static long PSV = 247;
    public final static long Puebla = 110152;
    public final static long QueensParkRangers = 15;
    public final static long Queretaro = 110150;
    public final static long QuilmesAtleticoClub = 110554;
    public final static long ROviedo = 110827;
    public final static long RSporting = 459;
    public final static long RValladolidCF = 462;
    public final static long RZaragoza = 244;
    public final static long RacingClub = 101085;
    public final static long RacingClubdeLens = 64;
    public final static long RandersFC = 1786;
    public final static long RangersFC = 86;
    public final static long RayoVallecano = 480;
    public final static long RBLeipzig = 112172;
    public final static long RCCelta = 450;
    public final static long RCDeportivo = 242;
    public final static long RCStrasbourgAlsace = 76;
    public final static long RCDEspanyol = 452;
    public final static long RCDMallorca = 453;
    public final static long Reading = 1793;
    public final static long RealBetis = 449;
    public final static long RealMadrid = 243;
    public final static long RealSaltLake = 111065;
    public final static long RealSociedad = 457;
    public final static long RedStarFC = 111273;
    public final static long RioAveFC = 744;
    public final static long RionegroAguilas = 112578;
    public final static long RiverPlate = 1876;
    public final static long Rochdale = 1955;
    public final static long RodaJCKerkrade = 1902;
    public final static long Roma = 52;
    public final static long RosarioCentral = 110580;
    public final static long RosenborgBK = 298;
    public final static long RossCountyFC = 631;
    public final static long RotherhamUnited = 1797;
    public final static long RoyalExcelMouscron = 111560;
    public final static long RSCAnderlecht = 229;
    public final static long RubinKazan = 110227;
    public final static long RuchChorzow = 874;
    public final static long SaganTosu = 113160;
    public final static long Salerno = 110373;
    public final static long Sampdoria = 1837;
    public final static long SanJoseEarthquakes = 111928;
    public final static long SanLorenzodeAlmagro = 1013;
    public final static long SanLuisdeQuillota = 112668;
    public final static long SanMartin = 111713;
    public final static long SanfrecceHiroshima = 113157;
    public final static long SangjuSangmuFC = 2055;
    public final static long SantiagoWanderers = 110976;
    public final static long SantosLaguna = 110144;
    public final static long Sarpsborg08FF = 112199;
    public final static long Sassuolo = 111974;
    public final static long SCBraga = 1896;
    public final static long SCHeerenveen = 1913;
    public final static long SCRAltach = 15009;
    public final static long ScunthorpeUnited = 1949;
    public final static long SDEibar = 467;
    public final static long SDHuesca = 110839;
    public final static long SeattleSoundersFC = 111144;
    public final static long SeongnamFC = 981;
    public final static long SevillaAtletico = 110714;
    public final static long SevillaFC = 481;
    public final static long SGDynamoDresden = 503;
    public final static long ShakhtarDonetsk = 101059;
    public final static long ShamrockRovers = 306;
    public final static long SheffieldUnited = 1794;
    public final static long SheffieldWednesday = 1807;
    public final static long ShonanBellmare = 113161;
    public final static long Shrewsbury = 127;
    public final static long SilkeborgIF = 270;
    public final static long SintTruidenseVV = 680;
    public final static long SKBrann = 919;
    public final static long SKRapidWien = 254;
    public final static long SKSturmGraz = 209;
    public final static long SKNStPolten = 112075;
    public final static long SLBenfica = 234;
    public final static long SlaskWroclaw = 111092;
    public final static long SligoRovers = 563;
    public final static long SogndalFotball = 1465;
    public final static long SonderjyskE = 1447;
    public final static long Southampton = 17;
    public final static long SouthendUnited = 1954;
    public final static long Spal = 112791;
    public final static long SpartaRotterdam = 100646;
    public final static long SpartakMoscow = 100767;
    public final static long SportClubFreiburg = 25;
    public final static long SportingCharleroi = 670;
    public final static long SportingClubdeBastia = 58;
    public final static long SportingCP = 237;
    public final static long SportingKansasCity = 696;
    public final static long SportingLokeren = 2007;
    public final static long SpVggGreutherFuerth = 165;
    public final static long StJohnstoneFC = 100804;
    public final static long StPatricksAthletic = 423;
    public final static long StabaekFotball = 917;
    public final static long StadeBrestois29 = 378;
    public final static long StadedeReims = 379;
    public final static long StadeLavalloisMayenneFC = 1814;
    public final static long StadeMalherbeCaen = 210;
    public final static long StadeRennaisFC = 74;
    public final static long StandarddeLiege = 232;
    public final static long Stevenage = 361;
    public final static long StokeCity = 1806;
    public final static long StromsgodsetIF = 922;
    public final static long Sunderland = 106;
    public final static long SuwonFC = 112558;
    public final static long SuwonSamsungBluewings = 983;
    public final static long SVDarmstadt98 = 110502;
    public final static long SVGuntamaticRied = 780;
    public final static long SVMattersburg = 1785;
    public final static long SVSandhausen = 110178;
    public final static long SVWerderBremen = 38;
    public final static long SVZulteWaregem = 15005;
    public final static long SwanseaCity = 1960;
    public final static long SwindonTown = 1934;
    public final static long SydneyFC = 111400;
    public final static long TerekGrozny = 110109;
    public final static long Terni = 570;
    public final static long TiburonesRojosdeVeracruz = 110145;
    public final static long TigresUANL = 1970;
    public final static long Tondela = 112516;
    public final static long Torino = 54;
    public final static long TorontoFC = 111651;
    public final static long TottenhamHotspur = 18;
    public final static long ToulouseFootballClub = 1809;
    public final static long ToursFootballClub = 110326;
    public final static long Trabzonspor = 436;
    public final static long Trapani = 112410;
    public final static long TromsoIL = 418;
    public final static long TSG1899Hoffenheim = 10029;
    public final static long TSV1860Munchen = 33;
    public final static long UNAM = 1881;
    public final static long UCAMMurciaCF = 113216;
    public final static long UDAlmeria = 1861;
    public final static long UDLasPalmas = 472;
    public final static long Udinese = 55;
    public final static long UlsanHyundaiHorangi = 1473;
    public final static long UniondeSantaFe = 111716;
    public final static long UnionEspanola = 110977;
    public final static long UniversidadCatolica = 110975;
    public final static long UniversidaddeChile = 15029;
    public final static long UrawaRedDiamonds = 111575;
    public final static long USOrleansLoiretFootball = 112276;
    public final static long ValenciaCF = 461;
    public final static long ValenciennesFC = 110456;
    public final static long ValerengaFotball = 920;
    public final static long VancouverWhitecapsFC = 101112;
    public final static long VegaltaSendai = 112836;
    public final static long VentforetKofu = 113162;
    public final static long Vercelli = 112398;
    public final static long VfBStuttgart = 36;
    public final static long VfLBochum1848 = 160;
    public final static long VfLWolfsburg = 175;
    public final static long ViborgFF = 1443;
    public final static long Vicenza = 112954;
    public final static long Victoria = 111715;
    public final static long VikingFK = 300;
    public final static long VillarrealCF = 483;
    public final static long VisselKobe = 101146;
    public final static long Vitesse = 1909;
    public final static long VitoriaGuimaraes = 1887;
    public final static long VitoriaSetubal = 665;
    public final static long WaaslandBeveren = 110913;
    public final static long Walsall = 1803;
    public final static long Watford = 1795;
    public final static long WellingtonPhoenix = 111766;
    public final static long WestBromwichAlbion = 109;
    public final static long WestHamUnited = 19;
    public final static long WesternSydneyWanderers = 112427;
    public final static long WexfordYouths = 111968;
    public final static long WiganAthletic = 1917;
    public final static long WillemII = 1907;
    public final static long WislaKrakow = 1873;
    public final static long WislaPlock = 1569;
    public final static long WolfsbergerAC = 111822;
    public final static long WolverhamptonWanderers = 110;
    public final static long WycombeWanderers = 1933;
    public final static long YeovilTown = 346;
    public final static long YokohamaFMarinos = 101151;
    public final static long ZaglebieLubin = 110749;
    public final static long ZenitStPetersburg = 100769;

    public Team(String description, long value, long league) {
        this.description = description;
        this.value = value;
        this.parent = league;
    }

    public static Collection<Team> getAll() {
        Collection<Team> teams = new ArrayList<>();

        teams.add(new Team("FC Heidenheim 1846", Heidenheim1846, League.Bundesliga2));
        teams.add(new Team("FC Kaiserslautern", Kaiserslautern, League.Bundesliga2));
        teams.add(new Team("FC Koln", Koln, League.Bundesliga));
        teams.add(new Team("FC Nurnberg", Nurnberg, League.Bundesliga2));
        teams.add(new Team("FC Union Berlin", UnionBerlin, League.Bundesliga2));
        teams.add(new Team("FSV Mainz 05", Mainz05, League.Bundesliga));
        teams.add(new Team("Aalborg BK", AalborgBK, League.AlkaSuperliga));
        teams.add(new Team("Aalesunds FK", AalesundsFK, League.Tippeligaen));
        teams.add(new Team("Aarhus GF", AarhusGF, League.AlkaSuperliga));
        teams.add(new Team("Aberdeen", Aberdeen, League.ScottishPremiership));
        teams.add(new Team("AC Horsens", ACHorsens, League.PremierLeague));
        teams.add(new Team("Accrington Stanley", AccringtonStanley, League.EFLLeagueTwo));
        teams.add(new Team("AD Alcorcon", ADAlcorcon, League.LaLiga123));
        teams.add(new Team("Adanaspor", Adanaspor, League.SuperLig));
        teams.add(new Team("Adelaide United", AdelaideUnited, League.HyundaiALeague));
        teams.add(new Team("ADO Den Haag", ADODenHaag, League.Eredivisie));
        teams.add(new Team("AFC Wimbledon", AFCWimbledon, League.EFLLeagueOne));
        teams.add(new Team("AIK", AIK, League.Allsvenskan));
        teams.add(new Team("AJ Auxerre", AJAuxerre, League.DominosLigue2));
        teams.add(new Team("Ajax", Ajax, League.Eredivisie));
        teams.add(new Team("Akhisar Belediyespor", AkhisarBelediyespor, League.SuperLig));
        teams.add(new Team("Al Ahli", AlAhli, League.DawryJameel));
        teams.add(new Team("Al Batin", AlBatin, League.DawryJameel));
        teams.add(new Team("Al Faisaly", AlFaisaly, League.DawryJameel));
        teams.add(new Team("Al Fateh", AlFateh, League.DawryJameel));
        teams.add(new Team("Al Hilal", AlHilal, League.DawryJameel));
        teams.add(new Team("Al Ittihad", AlIttihad, League.DawryJameel));
        teams.add(new Team("Al Khaleej", AlKhaleej, League.DawryJameel));
        teams.add(new Team("Al Nassr", AlNassr, League.DawryJameel));
        teams.add(new Team("Al Qadisiyah", AlQadisiyah, League.DawryJameel));
        teams.add(new Team("Al Raed", AlRaed, League.DawryJameel));
        teams.add(new Team("Al Shabab", AlShabab, League.DawryJameel));
        teams.add(new Team("Al Taawoun", AlTaawoun, League.DawryJameel));
        teams.add(new Team("Al Wehda", AlWehda, League.DawryJameel));
        teams.add(new Team("Alanyaspor", Alanyaspor, League.SuperLig));
        teams.add(new Team("Albirex Niigata", AlbirexNiigata, League.MeijiYasudaJ1League));
        teams.add(new Team("Alianza Petrolera", AlianzaPetrolera, League.LigaDimayor));
        teams.add(new Team("Amiens SC", AmiensSC, League.DominosLigue2));
        teams.add(new Team("Amkar Perm", AmkarPerm, League.RSL));
        teams.add(new Team("Angers SCO", AngersSCO, League.Ligue1));
        teams.add(new Team("Antalyaspor", Antalyaspor, League.SuperLig));
        teams.add(new Team("Arka Gdynia", ArkaGdynia, League.Ekstraklasa));
        teams.add(new Team("Arsenal", Arsenal, League.PremierLeague));
        teams.add(new Team("Arsenal de Sarandi", ArsenaldeSarandi, League.PrimeraDivision));
        teams.add(new Team("AS Monaco Football Club SA", ASMonacoFootballClubSA, League.Ligue1));
        teams.add(new Team("AS Nancy Lorraine", ASNancyLorraine, League.Ligue1));
        teams.add(new Team("AS Saint-Etienne", ASSaintEtienne, League.Ligue1));
        teams.add(new Team("Ascoli", Ascoli, League.CalcioB));
        teams.add(new Team("Aston Villa", AstonVilla, League.EFLChampionship));
        teams.add(new Team("Atalanta", Atalanta, League.CalcioA));
        teams.add(new Team("Athletic Club", AthleticClub, League.LaLigaSantander));
        teams.add(new Team("Athletic Club Ajaccio", AthleticClubAjaccio, League.DominosLigue2));
        teams.add(new Team("Atiker Konyaspor", AtikerKonyaspor, League.SuperLig));
        teams.add(new Team("Atletico Bucaramanga", AtleticoBucaramanga, League.LigaDimayor));
        teams.add(new Team("Atletico de Rafaela", AtleticodeRafaela, League.PrimeraDivision));
        teams.add(new Team("Atletico Huila", AtleticoHuila, League.LigaDimayor));
        teams.add(new Team("Atletico Madrid", AtleticoMadrid, League.LaLigaSantander));
        teams.add(new Team("Atletico Nacional", AtleticoNacional, League.LigaDimayor));
        teams.add(new Team("Atletico Tucuman", AtleticoTucuman, League.PrimeraDivision));
        teams.add(new Team("Audax Italiano", AudaxItaliano, League.CampScotiabank));
        teams.add(new Team("Avellino", Avellino, League.CalcioB));
        teams.add(new Team("Avispa Fukuoka", AvispaFukuoka, League.MeijiYasudaJ1League));
        teams.add(new Team("AZ", AZ, League.Eredivisie));
        teams.add(new Team("Bari", Bari, League.CalcioB));
        teams.add(new Team("Barnet", Barnet, League.EFLLeagueTwo));
        teams.add(new Team("Barnsley", Barnsley, League.EFLChampionship));
        teams.add(new Team("Bayer 04 Leverkusen", Bayer04Leverkusen, League.Bundesliga));
        teams.add(new Team("Belgrano de Cordoba", BelgranodeCordoba, League.PrimeraDivision));
        teams.add(new Team("Benevento", Benevento, League.CalcioB));
        teams.add(new Team("Besiktas JK", BesiktasJK, League.SuperLig));
        teams.add(new Team("Birmingham City", BirminghamCity, League.EFLChampionship));
        teams.add(new Team("BK Hacken", BKHacken, League.Allsvenskan));
        teams.add(new Team("Blackburn Rovers", BlackburnRovers, League.EFLChampionship));
        teams.add(new Team("Blackpool", Blackpool, League.EFLLeagueTwo));
        teams.add(new Team("Boavista FC", BoavistaFC, League.LigaNOS));
        teams.add(new Team("Boca Juniors", BocaJuniors, League.PrimeraDivision));
        teams.add(new Team("Bohemian FC", BohemianFC, League.SSEAirtricityLeague));
        teams.add(new Team("Bologna", Bologna, League.CalcioA));
        teams.add(new Team("Bolton Wanderers", BoltonWanderers, League.EFLLeagueOne));
        teams.add(new Team("Borussia Dortmund", BorussiaDortmund, League.Bundesliga));
        teams.add(new Team("Borussia Monchengladbach", BorussiaMonchengladbach, League.Bundesliga));
        teams.add(new Team("Bourg en Bresse Peronnas 01", BourgenBressePeronnas01, League.DominosLigue2));
        teams.add(new Team("Bournemouth", Bournemouth, League.PremierLeague));
        teams.add(new Team("Boyaca Chico FC", BoyacaChicoFC, League.LigaDimayor));
        teams.add(new Team("Bradford City", BradfordCity, League.EFLLeagueOne));
        teams.add(new Team("Bray Wanderers", BrayWanderers, League.SSEAirtricityLeague));
        teams.add(new Team("Brentford", Brentford, League.EFLChampionship));
        teams.add(new Team("Brescia", Brescia, League.CalcioB));
        teams.add(new Team("Brighton & Hove Albion", BrightonHoveAlbion, League.EFLChampionship));
        teams.add(new Team("Brisbane Roar", BrisbaneRoar, League.HyundaiALeague));
        teams.add(new Team("Bristol City", BristolCity, League.EFLChampionship));
        teams.add(new Team("Bristol Rovers", BristolRovers, League.EFLLeagueOne));
        teams.add(new Team("Brondby IF", BrondbyIF, League.AlkaSuperliga));
        teams.add(new Team("Bruk-Bet Termalica Nieciecza", BrukBetTermalicaNieciecza, League.Ekstraklasa));
        teams.add(new Team("BSC Young Boys", BSCYoungBoys, League.RSL));
        teams.add(new Team("Burnley", Burnley, League.PremierLeague));
        teams.add(new Team("Bursaspor", Bursaspor, League.SuperLig));
        teams.add(new Team("Burton Albion", BurtonAlbion, League.EFLChampionship));
        teams.add(new Team("Bury", Bury, League.EFLLeagueOne));
        teams.add(new Team("CA Osasuna", CAOsasuna, League.LaLigaSantander));
        teams.add(new Team("Cadiz CF", CadizCF, League.LaLiga123));
        teams.add(new Team("Cagliari", Cagliari, League.CalcioA));
        teams.add(new Team("Cambridge United", CambridgeUnited, League.EFLLeagueTwo));
        teams.add(new Team("Cardiff City", CardiffCity, League.EFLChampionship));
        teams.add(new Team("Carlisle United", CarlisleUnited, League.EFLLeagueTwo));
        teams.add(new Team("Carpi", Carpi, League.CalcioB));
        teams.add(new Team("Caykur Rizespor", CaykurRizespor, League.SuperLig));
        teams.add(new Team("CD Antofagasta", CDAntofagasta, League.CampScotiabank));
        teams.add(new Team("CD Cobresal", CDCobresal, League.CampScotiabank));
        teams.add(new Team("CD Everton de Vina del Mar", CDEvertondeVinadelMar, League.CampScotiabank));
        teams.add(new Team("CD Huachipato", CDHuachipato, League.CampScotiabank));
        teams.add(new Team("CD Leganes", CDLeganes, League.LaLigaSantander));
        teams.add(new Team("CD Lugo", CDLugo, League.LaLiga123));
        teams.add(new Team("CD Mirandes", CDMirandes, League.LaLiga123));
        teams.add(new Team("CD Nacional", CDNacional, League.LigaNOS));
        teams.add(new Team("CD Numancia", CDNumancia, League.LaLiga123));
        teams.add(new Team("CD O'Higgins", CDOHiggins, League.CampScotiabank));
        teams.add(new Team("CD Palestino", CDPalestino, League.CampScotiabank));
        teams.add(new Team("CD Tenerife", CDTenerife, League.LaLiga123));
        teams.add(new Team("CD Universidad de Concepcion", CDUniversidaddeConcepcion, League.CampScotiabank));
        teams.add(new Team("Celtic", Celtic, League.ScottishPremiership));
        teams.add(new Team("Central Coast Mariners", CentralCoastMariners, League.HyundaiALeague));
        teams.add(new Team("Cesena", Cesena, League.CalcioA));
        teams.add(new Team("CF Os Belenenses", CFOsBelenenses, League.LigaNOS));
        teams.add(new Team("CF Reus", CFReus, League.LaLiga123));
        teams.add(new Team("Chamois Niortais Football Club", ChamoisNiortaisFootballClub, League.DominosLigue2));
        teams.add(new Team("Charlton Athletic", CharltonAthletic, League.EFLLeagueOne));
        teams.add(new Team("Chaves", Chaves, League.LigaNOS));
        teams.add(new Team("Chelsea", Chelsea, League.PremierLeague));
        teams.add(new Team("Cheltenham Town", CheltenhamTown, League.EFLLeagueTwo));
        teams.add(new Team("Chesterfield", Chesterfield, League.EFLLeagueOne));
        teams.add(new Team("Chiavari", Chiavari, League.CalcioB));
        teams.add(new Team("Chicago Fire Soccer Club", ChicagoFireSoccerClub, League.MLS));
        teams.add(new Team("Chievo Verona", ChievoVerona, League.CalcioA));
        teams.add(new Team("Cittadella", Cittadella, League.CalcioB));
        teams.add(new Team("Clermont Foot 63", ClermontFoot63, League.DominosLigue2));
        teams.add(new Team("Club America", ClubAmerica, League.LIGABancomerMX));
        teams.add(new Team("Club Atlas", ClubAtlas, League.LIGABancomerMX));
        teams.add(new Team("Club Atletico Aldosivi", ClubAtleticoAldosivi, League.PrimeraDivision));
        teams.add(new Team("Club Atletico Banfield", ClubAtleticoBanfield, League.PrimeraDivision));
        teams.add(new Team("Club Atletico Huracan", ClubAtleticoHuracan, League.PrimeraDivision));
        teams.add(new Team("Club Atletico Lanus", ClubAtleticoLanus, League.PrimeraDivision));
        teams.add(new Team("Club Atletico Sarmiento", ClubAtleticoSarmiento, League.PrimeraDivision));
        teams.add(new Team("Club Atletico Talleres", ClubAtleticoTalleres, League.PrimeraDivision));
        teams.add(new Team("Club Atletico Temperley", ClubAtleticoTemperley, League.PrimeraDivision));
        teams.add(new Team("Club Brugge KV", ClubBruggeKV, League.ProLeague));
        teams.add(new Team("Club Deportes Temuco", ClubDeportesTemuco, League.CampScotiabank));
        teams.add(new Team("Club Leon", ClubLeon, League.LIGABancomerMX));
        teams.add(new Team("Club Necaxa", ClubNecaxa, League.LIGABancomerMX));
        teams.add(new Team("Club Olimpo", ClubOlimpo, League.PrimeraDivision));
        teams.add(new Team("Club Tijuana", ClubTijuana, League.LIGABancomerMX));
        teams.add(new Team("Colchester United", ColchesterUnited, League.EFLLeagueTwo));
        teams.add(new Team("Colo-Colo", ColoColo, League.CampScotiabank));
        teams.add(new Team("Colon de Santa Fe", ColondeSantaFe, League.PrimeraDivision));
        teams.add(new Team("Colorado Rapids", ColoradoRapids, League.MLS));
        teams.add(new Team("Columbus Crew SC", ColumbusCrewSC, League.MLS));
        teams.add(new Team("Cordoba CF", CordobaCF, League.LaLiga123));
        teams.add(new Team("Cork City", CorkCity, League.SSEAirtricityLeague));
        teams.add(new Team("Corporacion Club Deportivo Tulua", CorporacionClubDeportivoTulua, League.LigaDimayor));
        teams.add(new Team("Coventry City", CoventryCity, League.EFLLeagueOne));
        teams.add(new Team("Cracovia", Cracovia, League.Ekstraklasa));
        teams.add(new Team("Crawley Town", CrawleyTown, League.EFLLeagueTwo));
        teams.add(new Team("Crewe Alexandra", CreweAlexandra, League.EFLLeagueTwo));
        teams.add(new Team("Crotone", Crotone, League.CalcioA));
        teams.add(new Team("Cruz Azul", CruzAzul, League.LIGABancomerMX));
        teams.add(new Team("Crystal Palace", CrystalPalace, League.PremierLeague));
        teams.add(new Team("CS Maritimo", CSMaritimo, League.LigaNOS));
        teams.add(new Team("CSKA Moscow", CSKAMoscow, League.RSL));
        teams.add(new Team("D. Alaves", DAlaves, League.LaLigaSantander));
        teams.add(new Team("D.C. United", DCUnited, League.MLS));
        teams.add(new Team("Defensa y Justicia", DefensayJusticia, League.PrimeraDivision));
        teams.add(new Team("Deportes Iquique", DeportesIquique, League.CampScotiabank));
        teams.add(new Team("Deportes Tolima", DeportesTolima, League.LigaDimayor));
        teams.add(new Team("Deportivo Cali", DeportivoCali, League.LigaDimayor));
        teams.add(new Team("Deportivo Pasto", DeportivoPasto, League.LigaDimayor));
        teams.add(new Team("Deportivo Toluca", DeportivoToluca, League.LIGABancomerMX));
        teams.add(new Team("Derby County", DerbyCounty, League.EFLChampionship));
        teams.add(new Team("Derry City", DerryCity, League.SSEAirtricityLeague));
        teams.add(new Team("Dijon FCO", DijonFCO, League.Ligue1));
        teams.add(new Team("Djurgardens IF", DjurgardensIF, League.Allsvenskan));
        teams.add(new Team("Doncaster Rovers", DoncasterRovers, League.EFLLeagueTwo));
        teams.add(new Team("DSC Arminia Bielefeld", DSCArminiaBielefeld, League.Bundesliga2));
        teams.add(new Team("Dundalk", Dundalk, League.SSEAirtricityLeague));
        teams.add(new Team("Dundee FC", DundeeFC, League.ScottishPremiership));
        teams.add(new Team("Eintracht Braunschweig", EintrachtBraunschweig, League.Bundesliga2));
        teams.add(new Team("Eintracht Frankfurt", EintrachtFrankfurt, League.Bundesliga));
        teams.add(new Team("Elche CF", ElcheCF, League.LaLiga123));
        teams.add(new Team("Empoli", Empoli, League.CalcioA));
        teams.add(new Team("En Avant de Guingamp", EnAvantdeGuingamp, League.Ligue1));
        teams.add(new Team("Envigado FC", EnvigadoFC, League.LigaDimayor));
        teams.add(new Team("Esbjerg fB", EsbjergfB, League.AlkaSuperliga));
        teams.add(new Team("ESTAC Troyes", ESTACTroyes, League.DominosLigue2));
        teams.add(new Team("Estoril Praia", EstorilPraia, League.LigaNOS));
        teams.add(new Team("Estudiantes de La Plata", EstudiantesdeLaPlata, League.PrimeraDivision));
        teams.add(new Team("Ettifaq FC", EttifaqFC, League.DawryJameel));
        teams.add(new Team("Everton", Everton, League.PremierLeague));
        teams.add(new Team("Excelsior", Excelsior, League.Eredivisie));
        teams.add(new Team("Exeter City", ExeterCity, League.EFLLeagueTwo));
        teams.add(new Team("F. Santa Maria da Feira", FSantaMariadaFeira, League.LigaNOS));
        teams.add(new Team("F.C. Tokyo", FCTokyo, League.MeijiYasudaJ1League));
        teams.add(new Team("Falkenbergs FF", FalkenbergsFF, League.Allsvenskan));
        teams.add(new Team("FC Admira Wacker Modling", FCAdmiraWackerModling, League.OBundesliga));
        teams.add(new Team("FC Anzhi Makhachkala", FCAnzhiMakhachkala, League.RussianLeague));
        teams.add(new Team("FC Arouca", FCArouca, League.LigaNOS));
        teams.add(new Team("FC Arsenal Tula", FCArsenalTula, League.RussianLeague));
        teams.add(new Team("FC Augsburg", FCAugsburg, League.Bundesliga));
        teams.add(new Team("FC Barcelona", FCBarcelona, League.LaLigaSantander));
        teams.add(new Team("FC Basel", FCBasel, League.RSL));
        teams.add(new Team("FC Bayern Munchen", FCBayernMunchen, League.Bundesliga));
        teams.add(new Team("FC Dallas", FCDallas, League.MLS));
        teams.add(new Team("FC Erzgebirge Aue", FCErzgebirgeAue, League.Bundesliga2));
        teams.add(new Team("FC Girondins de Bordeaux", FCGirondinsdeBordeaux, League.Ligue1));
        teams.add(new Team("FC Groningen", FCGroningen, League.Eredivisie));
        teams.add(new Team("FC Ingolstadt 04", FCIngolstadt04, League.Bundesliga));
        teams.add(new Team("FC Kobenhavn", FCKobenhavn, League.AlkaSuperliga));
        teams.add(new Team("FC Krasnodar", FCKrasnodar, League.RussianLeague));
        teams.add(new Team("FC Krylya Sovetov Samara", FCKrylyaSovetovSamara, League.RussianLeague));
        teams.add(new Team("FC Lausanne-Sport", FCLausanneSport, League.RSL));
        teams.add(new Team("FC Lorient", FCLorient, League.Ligue1));
        teams.add(new Team("FC Lugano", FCLugano, League.RSL));
        teams.add(new Team("FC Luzern", FCLuzern, League.RSL));
        teams.add(new Team("FC Midtjylland", FCMidtjylland, League.AlkaSuperliga));
        teams.add(new Team("FC Nantes", FCNantes, League.Ligue1));
        teams.add(new Team("FC Nordsjaelland", FCNordsjaelland, League.AlkaSuperliga));
        teams.add(new Team("FC Orenburg", FCOrenburg, League.RussianLeague));
        teams.add(new Team("FC Pacos de Ferreira", FCPacosdeFerreira, League.LigaNOS));
        teams.add(new Team("FC Porto", FCPorto, League.LigaNOS));
        teams.add(new Team("FC Red Bull Salzburg", FCRedBullSalzburg, League.OBundesliga));
        teams.add(new Team("FC Rostov", FCRostov, League.RussianLeague));
        teams.add(new Team("FC Schalke 04", FCSchalke04, League.Bundesliga));
        teams.add(new Team("FC Seoul", FCSeoul, League.KLeagueClassic));
        teams.add(new Team("FC Sion", FCSion, League.RSL));
        teams.add(new Team("FC Sochaux-Montbeliard", FCSochauxMontbeliard, League.DominosLigue2));
        teams.add(new Team("FC St. Gallen", FCStGallen, League.RSL));
        teams.add(new Team("FC St. Pauli Hamburg", FCStPauliHamburg, League.Bundesliga2));
        teams.add(new Team("FC Thun", FCThun, League.RSL));
        teams.add(new Team("FC Tom Tomsk", FCTomTomsk, League.RussianLeague));
        teams.add(new Team("FC Twente", FCTwente, League.Eredivisie));
        teams.add(new Team("FC Ufa", FCUfa, League.RussianLeague));
        teams.add(new Team("FC Ural", FCUral, League.RussianLeague));
        teams.add(new Team("FC Utrecht", FCUtrecht, League.Eredivisie));
        teams.add(new Team("FC Vaduz", FCVaduz, League.RSL));
        teams.add(new Team("FC Wurzburger Kickers", FCWurzburgerKickers, League.Bundesliga2));
        teams.add(new Team("Fenerbahce SK", FenerbahceSK, League.SuperLig));
        teams.add(new Team("Ferrara", Ferrara, League.CalcioB));
        teams.add(new Team("Feyenoord", Feyenoord, League.Eredivisie));
        teams.add(new Team("Finn Harps", FinnHarps, League.SSEAirtricityLeague));
        teams.add(new Team("Fiorentina", Fiorentina, League.CalcioA));
        teams.add(new Team("FK Austria Wien", FKAustriaWien, League.OBundesliga));
        teams.add(new Team("FK Bodo/Glimt", FKBodoGlimt, League.Tippeligaen));
        teams.add(new Team("FK Haugesund", FKHaugesund, League.Tippeligaen));
        teams.add(new Team("Fleetwood Town", FleetwoodTown, League.EFLLeagueOne));
        teams.add(new Team("Football Club de Metz", FootballClubdeMetz, League.Ligue1));
        teams.add(new Team("Fortaleza CEIF", FortalezaCEIF, League.LigaDimayor));
        teams.add(new Team("Fortuna Dusseldorf", FortunaDusseldorf, League.Bundesliga2));
        teams.add(new Team("Frosinone", Frosinone, League.CalcioB));
        teams.add(new Team("Fulham", Fulham, League.EFLChampionship));
        teams.add(new Team("Galatasaray SK", GalatasaraySK, League.SuperLig));
        teams.add(new Team("Galway United", GalwayUnited, League.SSEAirtricityLeague));
        teams.add(new Team("Gamba Osaka", GambaOsaka, League.MeijiYasudaJ1League));
        teams.add(new Team("Gazelec Football Club Ajaccio", GazelecFootballClubAjaccio, League.DominosLigue2));
        teams.add(new Team("Gaziantepspor", Gaziantepspor, League.SuperLig));
        teams.add(new Team("Gefle IF", GefleIF, League.Allsvenskan));
        teams.add(new Team("Genclerbirligi SK", GenclerbirligiSK, League.SuperLig));
        teams.add(new Team("Genoa", Genoa, League.CalcioA));
        teams.add(new Team("Getafe CF", GetafeCF, League.LaLiga123));
        teams.add(new Team("GIF Sundsvall", GIFSundsvall, League.Allsvenskan));
        teams.add(new Team("Gillingham", Gillingham, League.EFLLeagueOne));
        teams.add(new Team("Gimnasia y Esgrima La Plata", GimnasiayEsgrimaLaPlata, League.PrimeraDivision));
        teams.add(new Team("Girona FC", GironaFC, League.LaLiga123));
        teams.add(new Team("Go Ahead Eagles", GoAheadEagles, League.Eredivisie));
        teams.add(new Team("Godoy Cruz", GodoyCruz, League.PrimeraDivision));
        teams.add(new Team("Gornik Leczna", GornikLeczna, League.Ekstraklasa));
        teams.add(new Team("Granada CF", GranadaCF, League.LaLigaSantander));
        teams.add(new Team("Grasshopper Club Zurich", GrasshopperClubZurich, League.RSL));
        teams.add(new Team("Grimsby Town", GrimsbyTown, League.EFLLeagueTwo));
        teams.add(new Team("Guadalajara", Guadalajara, League.LIGABancomerMX));
        teams.add(new Team("GwangJu FC", GwangJuFC, League.KLeagueClassic));
        teams.add(new Team("Hamburger SV", HamburgerSV, League.Bundesliga));
        teams.add(new Team("Hamilton Academical FC", HamiltonAcademicalFC, League.ScottishPremiership));
        teams.add(new Team("Hammarby IF", HammarbyIF, League.Allsvenskan));
        teams.add(new Team("Hannover 96", Hannover96, League.Bundesliga2));
        teams.add(new Team("Hartlepool United", HartlepoolUnited, League.EFLLeagueTwo));
        teams.add(new Team("Havre Athletic Club", HavreAthleticClub, League.DominosLigue2));
        teams.add(new Team("Heart of Midlothian", HeartofMidlothian, League.ScottishPremiership));
        teams.add(new Team("Hellas Verona", HellasVerona, League.CalcioB));
        teams.add(new Team("Helsingborgs IF", HelsingborgsIF, League.Allsvenskan));
        teams.add(new Team("Heracles Almelo", HeraclesAlmelo, League.Eredivisie));
        teams.add(new Team("Hertha Berlin", HerthaBerlin, League.Bundesliga));
        teams.add(new Team("HJK Helsinki", HJKHelsinki, League.Finnliiga));
        teams.add(new Team("Holstein Kiel", HolsteinKiel, League.Bundesliga2));
        teams.add(new Team("Houston Dynamo", HoustonDynamo, League.MLS));
        teams.add(new Team("Huddersfield Town", HuddersfieldTown, League.EFLChampionship));
        teams.add(new Team("Hull City", HullCity, League.PremierLeague));
        teams.add(new Team("IF Elfsborg", IFElfsborg, League.Allsvenskan));
        teams.add(new Team("IFK Goteborg", IFKGoteborg, League.Allsvenskan));
        teams.add(new Team("IFK Norrkoping", IFKNorrkoping, League.Allsvenskan));
        teams.add(new Team("IK Start", IKStart, League.Tippeligaen));
        teams.add(new Team("Incheon United FC", IncheonUnitedFC, League.KLeagueClassic));
        teams.add(new Team("Independiente", Independiente, League.PrimeraDivision));
        teams.add(new Team("Independiente Medellin", IndependienteMedellin, League.LigaDimayor));
        teams.add(new Team("Independiente Santa Fe", IndependienteSantaFe, League.LigaDimayor));
        teams.add(new Team("Inter", Inter, League.CalcioA));
        teams.add(new Team("Inverness Caledonian Thistle", InvernessCaledonianThistle, League.ScottishPremiership));
        teams.add(new Team("Ipswich Town", IpswichTown, League.EFLChampionship));
        teams.add(new Team("Jagiellonia Bialystok", JagielloniaBialystok, League.Ekstraklasa));
        teams.add(new Team("Jaguares de Chiapas", JaguaresdeChiapas, League.LIGABancomerMX));
        teams.add(new Team("Jaguares Futbol Club", JaguaresFutbolClub, League.LigaDimayor));
        teams.add(new Team("Jeju United FC", JejuUnitedFC, League.KLeagueClassic));
        teams.add(new Team("Jeonbuk Hyundai Motors", JeonbukHyundaiMotors, League.KLeagueClassic));
        teams.add(new Team("Jeonnam Dragons", JeonnamDragons, League.KLeagueClassic));
        teams.add(new Team("Jonkopings Sodra IF", JonkopingsSodraIF, League.Allsvenskan));
        teams.add(new Team("Jubilo Iwata", JubiloIwata, League.MeijiYasudaJ1League));
        teams.add(new Team("Junior FC", JuniorFC, League.LigaDimayor));
        teams.add(new Team("Juventus", Juventus, League.CalcioA));
        teams.add(new Team("KAA Gent", KAAGent, League.ProLeague));
        teams.add(new Team("Kaizer Chiefs", KaizerChiefs, League.SouthAfricanFL));
        teams.add(new Team("Kalmar FF", KalmarFF, League.Allsvenskan));
        teams.add(new Team("Kardemir Karabukspor", KardemirKarabukspor, League.SuperLig));
        teams.add(new Team("Karlsruher SC", KarlsruherSC, League.Bundesliga2));
        teams.add(new Team("KAS Eupen", KASEupen, League.ProLeague));
        teams.add(new Team("Kashima Antlers", KashimaAntlers, League.MeijiYasudaJ1League));
        teams.add(new Team("Kashiwa Reysol", KashiwaReysol, League.MeijiYasudaJ1League));
        teams.add(new Team("Kasimpasa SK", KasimpasaSK, League.SuperLig));
        teams.add(new Team("Kawasaki Frontale", KawasakiFrontale, League.MeijiYasudaJ1League));
        teams.add(new Team("Kayserispor", Kayserispor, League.SuperLig));
        teams.add(new Team("Kilmarnock", Kilmarnock, League.ScottishPremiership));
        teams.add(new Team("Korona Kielce", KoronaKielce, League.Ekstraklasa));
        teams.add(new Team("KRC Genk", KRCGenk, League.ProLeague));
        teams.add(new Team("KV Kortrijk", KVKortrijk, League.ProLeague));
        teams.add(new Team("KV Mechelen", KVMechelen, League.ProLeague));
        teams.add(new Team("KV Oostende", KVOostende, League.ProLeague));
        teams.add(new Team("KVC Westerlo", KVCWesterlo, League.ProLeague));
        teams.add(new Team("La Equidad", LaEquidad, League.LigaDimayor));
        teams.add(new Team("LA Galaxy", LAGalaxy, League.MLS));
        teams.add(new Team("La Spezia", LaSpezia, League.CalcioB));
        teams.add(new Team("Latina", Latina, League.CalcioB));
        teams.add(new Team("Lazio", Lazio, League.CalcioA));
        teams.add(new Team("Lech Poznan", LechPoznan, League.Ekstraklasa));
        teams.add(new Team("Lechia Gdansk", LechiaGdansk, League.Ekstraklasa));
        teams.add(new Team("Leeds United", LeedsUnited, League.EFLChampionship));
        teams.add(new Team("Legends", Legends, League.Legends));
        teams.add(new Team("Legia Warszawa", LegiaWarszawa, League.Ekstraklasa));
        teams.add(new Team("Leicester City", LeicesterCity, League.PremierLeague));
        teams.add(new Team("Levante UD", LevanteUD, League.LaLiga123));
        teams.add(new Team("Leyton Orient", LeytonOrient, League.EFLLeagueTwo));
        teams.add(new Team("Lillestrom SK", LillestromSK, League.Tippeligaen));
        teams.add(new Team("Liniers", Liniers, League.PrimeraDivision));
        teams.add(new Team("Liverpool", Liverpool, League.PremierLeague));
        teams.add(new Team("Lokomotiv Moscow", LokomotivMoscow, League.RussianLeague));
        teams.add(new Team("Longford Town", LongfordTown, League.SSEAirtricityLeague));
        teams.add(new Team("LOSC Lille", LOSCLille, League.Ligue1));
        teams.add(new Team("Luton Town", LutonTown, League.EFLLeagueTwo));
        teams.add(new Team("Lyngby BK", LyngbyBK, League.AlkaSuperliga));
        teams.add(new Team("Malaga CF", MalagaCF, League.LaLigaSantander));
        teams.add(new Team("Malmo FF", MalmoFF, League.Allsvenskan));
        teams.add(new Team("Manchester City", ManchesterCity, League.PremierLeague));
        teams.add(new Team("Manchester United", ManchesterUnited, League.PremierLeague));
        teams.add(new Team("Mansfield Town", MansfieldTown, League.EFLLeagueTwo));
        teams.add(new Team("Medipol Basaksehir FK", MedipolBasaksehirFK, League.SuperLig));
        teams.add(new Team("Melbourne City", MelbourneCity, League.HyundaiALeague));
        teams.add(new Team("Melbourne Victory", MelbourneVictory, League.HyundaiALeague));
        teams.add(new Team("Middlesbrough", Middlesbrough, League.PremierLeague));
        teams.add(new Team("Milan", Milan, League.CalcioA));
        teams.add(new Team("Millonarios FC", MillonariosFC, League.LigaDimayor));
        teams.add(new Team("Millwall", Millwall, League.EFLLeagueOne));
        teams.add(new Team("Milton Keynes Dons", MiltonKeynesDons, League.EFLLeagueOne));
        teams.add(new Team("Molde FK", MoldeFK, League.Tippeligaen));
        teams.add(new Team("Monarcas Morelia", MonarcasMorelia, League.LIGABancomerMX));
        teams.add(new Team("Monterrey", Monterrey, League.LIGABancomerMX));
        teams.add(new Team("Montpellier Herault SC", MontpellierHeraultSC, League.Ligue1));
        teams.add(new Team("Montreal Impact", MontrealImpact, League.MLS));
        teams.add(new Team("Morecambe", Morecambe, League.EFLLeagueTwo));
        teams.add(new Team("Moreirense FC", MoreirenseFC, League.LigaNOS));
        teams.add(new Team("Motherwell", Motherwell, League.ScottishPremiership));
        teams.add(new Team("N.E.C.", NEC, League.Eredivisie));
        teams.add(new Team("Nagoya Grampus", NagoyaGrampus, League.MeijiYasudaJ1League));
        teams.add(new Team("Napoli", Napoli, League.CalcioA));
        teams.add(new Team("Nastic", Nastic, League.LaLiga123));
        teams.add(new Team("New England Revolution", NewEnglandRevolution, League.MLS));
        teams.add(new Team("New York City Football Club", NewYorkCityFootballClub, League.MLS));
        teams.add(new Team("New York Red Bulls", NewYorkRedBulls, League.MLS));
        teams.add(new Team("Newcastle Jets", NewcastleJets, League.HyundaiALeague));
        teams.add(new Team("Newcastle United", NewcastleUnited, League.EFLChampionship));
        teams.add(new Team("Newell's Old Boys", NewellsOldBoys, League.PrimeraDivision));
        teams.add(new Team("Newport County", NewportCounty, League.EFLLeagueTwo));
        teams.add(new Team("Nimes Olympique", NimesOlympique, League.DominosLigue2));
        teams.add(new Team("Northampton Town", NorthamptonTown, League.EFLLeagueOne));
        teams.add(new Team("Norwich City", NorwichCity, League.EFLChampionship));
        teams.add(new Team("Nottingham Forest", NottinghamForest, League.EFLChampionship));
        teams.add(new Team("Notts County", NottsCounty, League.EFLLeagueTwo));
        teams.add(new Team("Novara", Novara, League.CalcioB));
        teams.add(new Team("Odds BK", OddsBK, League.Tippeligaen));
        teams.add(new Team("Odense Boldklub", OdenseBoldklub, League.AlkaSuperliga));
        teams.add(new Team("OGC Nice", OGCNice, League.Ligue1));
        teams.add(new Team("Oldham Athletic", OldhamAthletic, League.EFLLeagueOne));
        teams.add(new Team("Olympiacos CFP", OlympiacosCFP, League.HellasLiga));
        teams.add(new Team("Olympique de Marseille", OlympiquedeMarseille, League.Ligue1));
        teams.add(new Team("Olympique Lyonnais", OlympiqueLyonnais, League.Ligue1));
        teams.add(new Team("Omiya Ardija", OmiyaArdija, League.MeijiYasudaJ1League));
        teams.add(new Team("Once Caldas", OnceCaldas, League.LigaDimayor));
        teams.add(new Team("Orebro SK", OrebroSK, League.Allsvenskan));
        teams.add(new Team("Orlando City Soccer Club", OrlandoCitySoccerClub, League.MLS));
        teams.add(new Team("Orlando Pirates", OrlandoPirates, League.SouthAfricanFL));
        teams.add(new Team("Osmanlispor", Osmanlispor, League.SuperLig));
        teams.add(new Team("Ostersunds FK", OstersundsFK, League.Allsvenskan));
        teams.add(new Team("Oxford United", OxfordUnited, League.EFLLeagueOne));
        teams.add(new Team("Pachuca", Pachuca, League.LIGABancomerMX));
        teams.add(new Team("Palermo", Palermo, League.CalcioA));
        teams.add(new Team("Panathinaikos FC", PanathinaikosFC, League.HellasLiga));
        teams.add(new Team("PAOK", PAOK, League.HellasLiga));
        teams.add(new Team("Paris Saint-Germain", ParisSaintGermain, League.Ligue1));
        teams.add(new Team("Partick Thistle F.C.", PartickThistleFC, League.ScottishPremiership));
        teams.add(new Team("Patriotas Boyaca FC", PatriotasBoyacaFC, League.LigaDimayor));
        teams.add(new Team("Patronato", Patronato, League.PrimeraDivision));
        teams.add(new Team("PEC Zwolle", PECZwolle, League.Eredivisie));
        teams.add(new Team("Perth Glory", PerthGlory, League.HyundaiALeague));
        teams.add(new Team("Perugia", Perugia, League.CalcioB));
        teams.add(new Team("Pescara", Pescara, League.CalcioA));
        teams.add(new Team("Peterborough United", PeterboroughUnited, League.EFLLeagueOne));
        teams.add(new Team("Philadelphia Union", PhiladelphiaUnion, League.MLS));
        teams.add(new Team("Piast Gliwice", PiastGliwice, League.Ekstraklasa));
        teams.add(new Team("Pisa", Pisa, League.CalcioB));
        teams.add(new Team("Plymouth Argyle", PlymouthArgyle, League.EFLLeagueTwo));
        teams.add(new Team("Pogon Szczecin", PogonSzczecin, League.Ekstraklasa));
        teams.add(new Team("Pohang Steelers", PohangSteelers, League.KLeagueClassic));
        teams.add(new Team("Port Vale", PortVale, League.EFLLeagueOne));
        teams.add(new Team("Portland Timbers", PortlandTimbers, League.MLS));
        teams.add(new Team("Portsmouth", Portsmouth, League.EFLLeagueTwo));
        teams.add(new Team("Preston North End", PrestonNorthEnd, League.EFLChampionship));
        teams.add(new Team("PSV", PSV, League.Eredivisie));
        teams.add(new Team("Puebla", Puebla, League.LIGABancomerMX));
        teams.add(new Team("Queens Park Rangers", QueensParkRangers, League.EFLChampionship));
        teams.add(new Team("Queretaro", Queretaro, League.LIGABancomerMX));
        teams.add(new Team("Quilmes Atletico Club", QuilmesAtleticoClub, League.PrimeraDivision));
        teams.add(new Team("R. Oviedo", ROviedo, League.LaLiga123));
        teams.add(new Team("R. Sporting", RSporting, League.LaLigaSantander));
        teams.add(new Team("R. Valladolid CF", RValladolidCF, League.LaLiga123));
        teams.add(new Team("R. Zaragoza", RZaragoza, League.LaLiga123));
        teams.add(new Team("Racing Club", RacingClub, League.PrimeraDivision));
        teams.add(new Team("Racing Club de Lens", RacingClubdeLens, League.DominosLigue2));
        teams.add(new Team("Randers FC", RandersFC, League.AlkaSuperliga));
        teams.add(new Team("Rangers FC", RangersFC, League.ScottishPremiership));
        teams.add(new Team("Rayo Vallecano", RayoVallecano, League.LaLiga123));
        teams.add(new Team("RB Leipzig", RBLeipzig, League.Bundesliga));
        teams.add(new Team("RC Celta", RCCelta, League.LaLigaSantander));
        teams.add(new Team("RC Deportivo", RCDeportivo, League.LaLigaSantander));
        teams.add(new Team("RC Strasbourg Alsace", RCStrasbourgAlsace, League.DominosLigue2));
        teams.add(new Team("RCD Espanyol", RCDEspanyol, League.LaLigaSantander));
        teams.add(new Team("RCD Mallorca", RCDMallorca, League.LaLiga123));
        teams.add(new Team("Reading", Reading, League.EFLChampionship));
        teams.add(new Team("Real Betis", RealBetis, League.LaLigaSantander));
        teams.add(new Team("Real Madrid", RealMadrid, League.LaLigaSantander));
        teams.add(new Team("Real Salt Lake", RealSaltLake, League.MLS));
        teams.add(new Team("Real Sociedad", RealSociedad, League.LaLigaSantander));
        teams.add(new Team("Red Star FC", RedStarFC, League.DominosLigue2));
        teams.add(new Team("Rio Ave FC", RioAveFC, League.LigaNOS));
        teams.add(new Team("Rionegro Aguilas", RionegroAguilas, League.LigaDimayor));
        teams.add(new Team("River Plate", RiverPlate, League.PrimeraDivision));
        teams.add(new Team("Rochdale", Rochdale, League.EFLLeagueOne));
        teams.add(new Team("Roda JC Kerkrade", RodaJCKerkrade, League.Eredivisie));
        teams.add(new Team("Roma", Roma, League.CalcioA));
        teams.add(new Team("Rosario Central", RosarioCentral, League.PrimeraDivision));
        teams.add(new Team("Rosenborg BK", RosenborgBK, League.Tippeligaen));
        teams.add(new Team("Ross County FC", RossCountyFC, League.ScottishPremiership));
        teams.add(new Team("Rotherham United", RotherhamUnited, League.EFLChampionship));
        teams.add(new Team("Royal Excel Mouscron", RoyalExcelMouscron, League.ProLeague));
        teams.add(new Team("RSC Anderlecht", RSCAnderlecht, League.ProLeague));
        teams.add(new Team("Rubin Kazan", RubinKazan, League.RussianLeague));
        teams.add(new Team("Ruch Chorzow", RuchChorzow, League.Ekstraklasa));
        teams.add(new Team("Sagan Tosu", SaganTosu, League.MeijiYasudaJ1League));
        teams.add(new Team("Salerno", Salerno, League.CalcioB));
        teams.add(new Team("Sampdoria", Sampdoria, League.CalcioA));
        teams.add(new Team("San Jose Earthquakes", SanJoseEarthquakes, League.MLS));
        teams.add(new Team("San Lorenzo de Almagro", SanLorenzodeAlmagro, League.PrimeraDivision));
        teams.add(new Team("San Luis de Quillota", SanLuisdeQuillota, League.CampScotiabank));
        teams.add(new Team("San Martin", SanMartin, League.PrimeraDivision));
        teams.add(new Team("Sanfrecce Hiroshima", SanfrecceHiroshima, League.MeijiYasudaJ1League));
        teams.add(new Team("Sangju Sangmu FC", SangjuSangmuFC, League.KLeagueClassic));
        teams.add(new Team("Santiago Wanderers", SantiagoWanderers, League.CampScotiabank));
        teams.add(new Team("Santos Laguna", SantosLaguna, League.LIGABancomerMX));
        teams.add(new Team("Sarpsborg 08 FF", Sarpsborg08FF, League.Tippeligaen));
        teams.add(new Team("Sassuolo", Sassuolo, League.CalcioA));
        teams.add(new Team("SC Braga", SCBraga, League.LigaNOS));
        teams.add(new Team("SC Heerenveen", SCHeerenveen, League.Eredivisie));
        teams.add(new Team("SCR Altach", SCRAltach, League.OBundesliga));
        teams.add(new Team("Scunthorpe United", ScunthorpeUnited, League.EFLLeagueOne));
        teams.add(new Team("SD Eibar", SDEibar, League.LaLigaSantander));
        teams.add(new Team("SD Huesca", SDHuesca, League.LaLiga123));
        teams.add(new Team("Seattle Sounders FC", SeattleSoundersFC, League.MLS));
        teams.add(new Team("Seongnam FC", SeongnamFC, League.KLeagueClassic));
        teams.add(new Team("Sevilla Atletico", SevillaAtletico, League.LaLiga123));
        teams.add(new Team("Sevilla FC", SevillaFC, League.LaLigaSantander));
        teams.add(new Team("SG Dynamo Dresden", SGDynamoDresden, League.Bundesliga2));
        teams.add(new Team("Shakhtar Donetsk", ShakhtarDonetsk, League.UkrayinaLiha));
        teams.add(new Team("Shamrock Rovers", ShamrockRovers, League.SSEAirtricityLeague));
        teams.add(new Team("Sheffield United", SheffieldUnited, League.EFLLeagueOne));
        teams.add(new Team("Sheffield Wednesday", SheffieldWednesday, League.EFLChampionship));
        teams.add(new Team("Shonan Bellmare", ShonanBellmare, League.MeijiYasudaJ1League));
        teams.add(new Team("Shrewsbury", Shrewsbury, League.EFLLeagueOne));
        teams.add(new Team("Silkeborg IF", SilkeborgIF, League.AlkaSuperliga));
        teams.add(new Team("Sint-Truidense VV", SintTruidenseVV, League.ProLeague));
        teams.add(new Team("SK Brann", SKBrann, League.Tippeligaen));
        teams.add(new Team("SK Rapid Wien", SKRapidWien, League.OBundesliga));
        teams.add(new Team("SK Sturm Graz", SKSturmGraz, League.OBundesliga));
        teams.add(new Team("SKN St. Polten", SKNStPolten, League.OBundesliga));
        teams.add(new Team("SL Benfica", SLBenfica, League.LigaNOS));
        teams.add(new Team("Slask Wroclaw", SlaskWroclaw, League.Ekstraklasa));
        teams.add(new Team("Sligo Rovers", SligoRovers, League.SSEAirtricityLeague));
        teams.add(new Team("Sogndal Fotball", SogndalFotball, League.Tippeligaen));
        teams.add(new Team("SonderjyskE", SonderjyskE, League.AlkaSuperliga));
        teams.add(new Team("Southampton", Southampton, League.PremierLeague));
        teams.add(new Team("Southend United", SouthendUnited, League.EFLLeagueOne));
        teams.add(new Team("Spal", Spal, League.CalcioA));
        teams.add(new Team("Sparta Rotterdam", SpartaRotterdam, League.Eredivisie));
        teams.add(new Team("Spartak Moscow", SpartakMoscow, League.RussianLeague));
        teams.add(new Team("Sport-Club Freiburg", SportClubFreiburg, League.Bundesliga));
        teams.add(new Team("Sporting Charleroi", SportingCharleroi, League.ProLeague));
        teams.add(new Team("Sporting Club de Bastia", SportingClubdeBastia, League.Ligue1));
        teams.add(new Team("Sporting CP", SportingCP, League.LigaNOS));
        teams.add(new Team("Sporting Kansas City", SportingKansasCity, League.MLS));
        teams.add(new Team("Sporting Lokeren", SportingLokeren, League.ProLeague));
        teams.add(new Team("SpVgg Greuther Fuerth", SpVggGreutherFuerth, League.Bundesliga2));
        teams.add(new Team("St. Johnstone FC", StJohnstoneFC, League.ScottishPremiership));
        teams.add(new Team("St. Patrick's Athletic", StPatricksAthletic, League.SSEAirtricityLeague));
        teams.add(new Team("Stabaek Fotball", StabaekFotball, League.Tippeligaen));
        teams.add(new Team("Stade Brestois 29", StadeBrestois29, League.DominosLigue2));
        teams.add(new Team("Stade de Reims", StadedeReims, League.DominosLigue2));
        teams.add(new Team("Stade Lavallois Mayenne FC", StadeLavalloisMayenneFC, League.DominosLigue2));
        teams.add(new Team("Stade Malherbe Caen", StadeMalherbeCaen, League.Ligue1));
        teams.add(new Team("Stade Rennais FC", StadeRennaisFC, League.Ligue1));
        teams.add(new Team("Standard de Liege", StandarddeLiege, League.ProLeague));
        teams.add(new Team("Stevenage", Stevenage, League.EFLLeagueTwo));
        teams.add(new Team("Stoke City", StokeCity, League.PremierLeague));
        teams.add(new Team("Stromsgodset IF", StromsgodsetIF, League.Tippeligaen));
        teams.add(new Team("Sunderland", Sunderland, League.PremierLeague));
        teams.add(new Team("Suwon FC", SuwonFC, League.KLeagueClassic));
        teams.add(new Team("Suwon Samsung Bluewings", SuwonSamsungBluewings, League.KLeagueClassic));
        teams.add(new Team("SV Darmstadt 98", SVDarmstadt98, League.Bundesliga));
        teams.add(new Team("SV Guntamatic Ried", SVGuntamaticRied, League.OBundesliga));
        teams.add(new Team("SV Mattersburg", SVMattersburg, League.OBundesliga));
        teams.add(new Team("SV Sandhausen", SVSandhausen, League.Bundesliga2));
        teams.add(new Team("SV Werder Bremen", SVWerderBremen, League.Bundesliga));
        teams.add(new Team("SV Zulte-Waregem", SVZulteWaregem, League.ProLeague));
        teams.add(new Team("Swansea City", SwanseaCity, League.PremierLeague));
        teams.add(new Team("Swindon Town", SwindonTown, League.EFLLeagueOne));
        teams.add(new Team("Sydney FC", SydneyFC, League.HyundaiALeague));
        teams.add(new Team("Terek Grozny", TerekGrozny, League.RussianLeague));
        teams.add(new Team("Terni", Terni, League.CalcioB));
        teams.add(new Team("Tiburones Rojos de Veracruz", TiburonesRojosdeVeracruz, League.LIGABancomerMX));
        teams.add(new Team("Tigres U.A.N.L.", TigresUANL, League.LIGABancomerMX));
        teams.add(new Team("Tondela", Tondela, League.LigaNOS));
        teams.add(new Team("Torino", Torino, League.CalcioA));
        teams.add(new Team("Toronto FC", TorontoFC, League.MLS));
        teams.add(new Team("Tottenham Hotspur", TottenhamHotspur, League.PremierLeague));
        teams.add(new Team("Toulouse Football Club", ToulouseFootballClub, League.Ligue1));
        teams.add(new Team("Tours Football Club", ToursFootballClub, League.DominosLigue2));
        teams.add(new Team("Trabzonspor", Trabzonspor, League.SuperLig));
        teams.add(new Team("Trapani", Trapani, League.CalcioB));
        teams.add(new Team("Tromso IL", TromsoIL, League.Tippeligaen));
        teams.add(new Team("TSG 1899 Hoffenheim", TSG1899Hoffenheim, League.Bundesliga));
        teams.add(new Team("TSV 1860 Munchen", TSV1860Munchen, League.Bundesliga2));
        teams.add(new Team("U.N.A.M.", UNAM, League.LIGABancomerMX));
        teams.add(new Team("UCAM Murcia CF", UCAMMurciaCF, League.LaLiga123));
        teams.add(new Team("UD Almeria", UDAlmeria, League.LaLiga123));
        teams.add(new Team("UD Las Palmas", UDLasPalmas, League.LaLigaSantander));
        teams.add(new Team("Udinese", Udinese, League.CalcioA));
        teams.add(new Team("Ulsan Hyundai Horang-i", UlsanHyundaiHorangi, League.KLeagueClassic));
        teams.add(new Team("Union de Santa Fe", UniondeSantaFe, League.PrimeraDivision));
        teams.add(new Team("Union Espanola", UnionEspanola, League.CampScotiabank));
        teams.add(new Team("Universidad Catolica", UniversidadCatolica, League.CampScotiabank));
        teams.add(new Team("Universidad de Chile", UniversidaddeChile, League.CampScotiabank));
        teams.add(new Team("Urawa Red Diamonds", UrawaRedDiamonds, League.MeijiYasudaJ1League));
        teams.add(new Team("US Orleans Loiret Football", USOrleansLoiretFootball, League.DominosLigue2));
        teams.add(new Team("Valencia CF", ValenciaCF, League.LaLigaSantander));
        teams.add(new Team("Valenciennes FC", ValenciennesFC, League.DominosLigue2));
        teams.add(new Team("Valerenga Fotball", ValerengaFotball, League.Tippeligaen));
        teams.add(new Team("Vancouver Whitecaps FC", VancouverWhitecapsFC, League.MLS));
        teams.add(new Team("Vegalta Sendai", VegaltaSendai, League.MeijiYasudaJ1League));
        teams.add(new Team("Ventforet Kofu", VentforetKofu, League.MeijiYasudaJ1League));
        teams.add(new Team("Vercelli", Vercelli, League.CalcioB));
        teams.add(new Team("VfB Stuttgart", VfBStuttgart, League.Bundesliga2));
        teams.add(new Team("VfL Bochum 1848", VfLBochum1848, League.Bundesliga2));
        teams.add(new Team("VfL Wolfsburg", VfLWolfsburg, League.Bundesliga));
        teams.add(new Team("Viborg FF", ViborgFF, League.AlkaSuperliga));
        teams.add(new Team("Vicenza", Vicenza, League.CalcioB));
        teams.add(new Team("Victoria", Victoria, League.PrimeraDivision));
        teams.add(new Team("Viking FK", VikingFK, League.Tippeligaen));
        teams.add(new Team("Villarreal CF", VillarrealCF, League.LaLigaSantander));
        teams.add(new Team("Vissel Kobe", VisselKobe, League.MeijiYasudaJ1League));
        teams.add(new Team("Vitesse", Vitesse, League.Eredivisie));
        teams.add(new Team("Vitoria Guimaraes", VitoriaGuimaraes, League.LigaNOS));
        teams.add(new Team("Vitoria Setubal", VitoriaSetubal, League.LigaNOS));
        teams.add(new Team("Waasland-Beveren", WaaslandBeveren, League.ProLeague));
        teams.add(new Team("Walsall", Walsall, League.EFLLeagueOne));
        teams.add(new Team("Watford", Watford, League.PremierLeague));
        teams.add(new Team("Wellington Phoenix", WellingtonPhoenix, League.HyundaiALeague));
        teams.add(new Team("West Bromwich Albion", WestBromwichAlbion, League.PremierLeague));
        teams.add(new Team("West Ham United", WestHamUnited, League.PremierLeague));
        teams.add(new Team("Western Sydney Wanderers", WesternSydneyWanderers, League.HyundaiALeague));
        teams.add(new Team("Wexford Youths", WexfordYouths, League.SSEAirtricityLeague));
        teams.add(new Team("Wigan Athletic", WiganAthletic, League.EFLChampionship));
        teams.add(new Team("Willem II", WillemII, League.Eredivisie));
        teams.add(new Team("Wisla Krakow", WislaKrakow, League.Ekstraklasa));
        teams.add(new Team("Wisla Plock", WislaPlock, League.Ekstraklasa));
        teams.add(new Team("Wolfsberger AC", WolfsbergerAC, League.OBundesliga));
        teams.add(new Team("Wolverhampton Wanderers", WolverhamptonWanderers, League.EFLChampionship));
        teams.add(new Team("Wycombe Wanderers", WycombeWanderers, League.EFLLeagueTwo));
        teams.add(new Team("Yeovil Town", YeovilTown, League.EFLLeagueTwo));
        teams.add(new Team("Yokohama F. Marinos", YokohamaFMarinos, League.MeijiYasudaJ1League));
        teams.add(new Team("Zaglebie Lubin", ZaglebieLubin, League.Ekstraklasa));
        teams.add(new Team("Zenit St. Petersburg", ZenitStPetersburg, League.RussianLeague));

        return teams;
    }

    public static Integer getRandom() {
        Random random = new Random();
        List<Team> teams = new ArrayList<>(getAll());
        int i = random.nextInt(teams.size());
        return Math.toIntExact(teams.get(i).getValue());
    }
}
